if (typeof FILE_EXT === "undefined" || FILE_EXT === null || FILE_EXT === "") {
    return;
}

switch (FILE_EXT) {

    case "PDF":
        return "sap-icon://fa-solid/file-pdf";

    case "DOC":
    case "DOCX":
        return "sap-icon://fa-solid/file-word";

    case "JPG":
    case "JPEG":
    case "PNG":
        return "sap-icon://fa-solid/file-image";

    default:
        return "sap-icon://fa-solid/file";

}