const order = modelOrder.getData().order;
const customerId = order.customerId;
if (Number(order.status) > 2) {
    modelAppCtrl.getData().editMode = false;
} else {
    modelAppCtrl.getData().editMode = true;
}

modelAppCtrl.refresh();

var options = {
    parameters: {
        customerId,
    },
};
console.log(options);
apiGetCustomerDetails(options);

debugger;
setDetailsTableHeaderText();
